# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Redis
  # You may pin to the exact commit or the version.
  # uses: zhulik/redis-action@765216a54a1114f109ce90a1de4775080be16ea5
      uses: zhulik/redis-action@1.1.0
      with:
    # Version of Redis to use
        redis version: latest
    # Number of Redis databases
        number of databases: 16
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Build with Maven
      run: mvn package 
    - name: Deploy app build to S3 bucket
      run: aws s3 sync ./devops-challenge-web-service/target/ s3://mychallengebucket 
